import {identify,packed,tint,fields,labels,idOf} from './ownership.js';
const $=s=>document.querySelector(s),cv=$('#canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});
const names={'standard-i':'Standard I','spiral-i':'Spiral I',smk:'SMK',smlee:'SMLEE','em-rocket':'EM Rocket','closed-diamond-net':'Closed Diamond Net','modified-trapeze':'Modified Trapeze',trapeze:'Trapeze'},views={back:'Achterkant',palm:'Palm',thumb:'Duim'};
let manifest,refs,entry,view='back',source=false,mirror=false,mapView=false,isolate=false,selected='',pixels,map,colors={},revision=0,loading=true;
function busy(){loading=true;for(const id of ['parts','apply','reset','map','isolate','export','mask'])$('#'+id).disabled=true;$('#download').style.pointerEvents='none';$('#download').removeAttribute('href');$('#download').setAttribute('aria-disabled','true');}
const draw=()=>{if(!pixels)return;let im=source?pixels:tint(pixels,map,colors,selected,mapView);if(isolate&&selected&&!source){im=new ImageData(new Uint8ClampedArray(im.data),im.width,im.height);for(let i=0;i<map.ids.length;i++)if(map.ids[i]!==idOf(selected))im.data[i*4+3]=0;}ctx.putImageData(im,0,0);cv.style.transform=mirror?'scaleX(-1)':'';$('#selected').textContent=selected?labels[selected]:'Geen onderdeel geselecteerd';$('#parts').value=selected;$('#mask').disabled=!selected||source;$('#apply').disabled=!selected||source;$('#isolate').disabled=!selected||source;$('#export').disabled=source;$('#map').disabled=source;};
function blobDownload(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function updateZoom(){const z=Number($('#zoom').value);$('#stage').classList.toggle('zoom',z>1);$('#stage').style.setProperty('--zoom',z*100+'%');}
async function show(){if(!manifest||!refs)return;const token=++revision;busy();$('#status').textContent='Beeld laden…';entry=manifest.entries.find(x=>x.web===$('#web').value&&x.view===view);const ref=refs.rows.find(x=>x.slug===entry.web&&x.view===view);let src=source?ref.file:entry.image;const img=new Image();img.src=src;try{await img.decode();}catch(e){if(token===revision)$('#status').textContent='Dit beeld kon niet laden. Probeer een andere hoek.';return;}if(token!==revision)return;cv.width=img.naturalWidth;cv.height=img.naturalHeight;ctx.drawImage(img,0,0);pixels=ctx.getImageData(0,0,cv.width,cv.height);map=identify(pixels,view);colors={};selected='';isolate=false;$('#isolate').setAttribute('aria-pressed','false');$('#parts').innerHTML='<option value="">Alle onderdelen</option>';for(const role of fields.filter(x=>map.counts[x])){const o=document.createElement('option');o.value=role;o.textContent=labels[role];$('#parts').append(o);}$('#size').textContent=`${cv.width} × ${cv.height} · ${names[entry.web]} · ${views[view]}`;$('#download').href=entry.image;for(const b of $('#views').children)b.setAttribute('aria-pressed',b.dataset.view===view);$('#source').setAttribute('aria-pressed',String(source));$('#view-note').textContent=source&&view==='thumb'&&!ref.actualWeb?'Basisrenderer-export: deze vergelijking bevat voor dit web alleen de H-web basis. Dit is geen duimreferentie van het gekozen web.':view==='palm'?'Geschatte binnenzijde. Palm en binnenkant duim horen bij hetzelfde leer. Het onderste S + SSK-merkteken staat onder het ronde stempel.':view==='thumb'?'Geschatte duimhoek. Controleer aansluiting op palmleer, de logo-stikrand en alle openingen.':'Controleer de webconstructie en de losse aansluiting op het palmleer onder het web.';$('#status').textContent=source?'Huidige renderer als referentie.':'HD beeld · onderdelenkaart is een concept, niet geïnstalleerd in de configurator.';$('#parts').disabled=false;$('#reset').disabled=false;$('#download').style.pointerEvents='';$('#download').removeAttribute('aria-disabled');loading=false;draw();cards();if(entry.reviewNotes?.length)$('#view-note').textContent+=' Open punten: '+entry.reviewNotes.join(' · ');}
function cards(){const box=$('#cards');box.innerHTML='';for(const web of Object.keys(names)){const r=manifest.entries.find(x=>x.web===web&&x.view===view),b=document.createElement('button');b.className='card';b.setAttribute('aria-pressed',web===entry.web);const img=document.createElement('img');img.src=r.preview;img.loading='lazy';img.decoding='async';img.width=300;img.height=355;img.alt=names[web]+' · '+views[view];const cap=document.createElement('span');cap.textContent=names[web];b.append(img,cap);b.onclick=()=>{$('#web').value=web;show();};box.append(b);}}
for(const [v,title]of Object.entries(views)){const b=document.createElement('button');b.textContent=title;b.dataset.view=v;b.disabled=true;b.onclick=()=>{view=v;show();};$('#views').append(b);}
for(const [key,label]of Object.entries(names)){const o=document.createElement('option');o.value=key;o.textContent=label;$('#web').append(o);}$('#web').value='smlee';
$('#web').onchange=show;$('#zoom').onchange=updateZoom;$('#background').onchange=()=>document.documentElement.style.setProperty('--bg',$('#background').value);
$('#mirror').onclick=()=>{mirror=!mirror;$('#mirror').setAttribute('aria-pressed',mirror);draw();};$('#source').onclick=()=>{source=!source;show();};
$('#parts').onchange=()=>{selected=$('#parts').value;draw();};cv.onclick=e=>{if(source||loading||!map)return;const r=cv.getBoundingClientRect();let x=Math.floor((e.clientX-r.left)/r.width*cv.width),y=Math.floor((e.clientY-r.top)/r.height*cv.height);if(mirror)x=cv.width-1-x;const id=map.ids[y*cv.width+x];selected=id?fields[id-1]:'';draw();};
$('#apply').onclick=()=>{if(selected){colors[selected]=$('#color').value;draw();}};$('#reset').onclick=()=>{colors={};draw();};$('#map').onclick=()=>{mapView=!mapView;$('#map').setAttribute('aria-pressed',mapView);draw();};$('#isolate').onclick=()=>{isolate=!isolate;$('#isolate').setAttribute('aria-pressed',isolate);draw();};
$('#export').onclick=()=>blobDownload(new Blob([JSON.stringify({...packed(map),web:entry.web,view,image:entry.image,colors},null,2)],{type:'application/json'}),`ssk-hd-${entry.web}-${view}-onderdelen-concept.json`);
$('#mask').onclick=()=>{if(!selected)return;const id=idOf(selected),lines=[];for(let y=0;y<map.h;y++){let start=-1;for(let x=0;x<=map.w;x++){const on=x<map.w&&map.ids[y*map.w+x]===id;if(on&&start<0)start=x;if(!on&&start>=0){lines.push(`M${start} ${y}h${x-start}v1h-${x-start}z`);start=-1;}}}blobDownload(new Blob([`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${map.w} ${map.h}"><title>UNVERIFIED DRAFT ${selected}</title><path fill="white" d="${lines.join('')}"/></svg>`],{type:'image/svg+xml'}),`ssk-hd-${entry.web}-${view}-${selected}-masker-concept.svg`);};
busy();
try{[manifest,refs]=await Promise.all(['MANIFEST.json','REFERENCES.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw new Error(x);return r.json();})));await show();for(const id of ['web','source','mirror'])$('#'+id).disabled=false;for(const b of $('#views').children)b.disabled=false;}catch(e){$('#status').textContent='Het beeldmanifest kon niet laden. Herlaad deze pagina.';console.error(e);}
window.hdStudio={get state(){return {web:entry?.web,view,source,mirror,selected,colors,counts:map?.counts};},identify,packed};
